// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.23.4
// source: common.proto

package proto

import (
	_ "github.com/stroppy-io/stroppy-core/pkg/proto/gen/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value_NullValue int32

const (
	// * Null value
	Value_NULL_VALUE Value_NullValue = 0
)

// Enum value maps for Value_NullValue.
var (
	Value_NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	Value_NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x Value_NullValue) Enum() *Value_NullValue {
	p := new(Value_NullValue)
	*p = x
	return p
}

func (x Value_NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Value_NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Value_NullValue) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Value_NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Value_NullValue.Descriptor instead.
func (Value_NullValue) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3, 0}
}

type Generation_Distribution_DistributionType int32

const (
	// * Normal (Gaussian) distribution
	Generation_Distribution_NORMAL Generation_Distribution_DistributionType = 0
	// * Uniform distribution
	Generation_Distribution_UNIFORM Generation_Distribution_DistributionType = 1
	// * Zipfian distribution
	Generation_Distribution_ZIPF Generation_Distribution_DistributionType = 2
)

// Enum value maps for Generation_Distribution_DistributionType.
var (
	Generation_Distribution_DistributionType_name = map[int32]string{
		0: "NORMAL",
		1: "UNIFORM",
		2: "ZIPF",
	}
	Generation_Distribution_DistributionType_value = map[string]int32{
		"NORMAL":  0,
		"UNIFORM": 1,
		"ZIPF":    2,
	}
)

func (x Generation_Distribution_DistributionType) Enum() *Generation_Distribution_DistributionType {
	p := new(Generation_Distribution_DistributionType)
	*p = x
	return p
}

func (x Generation_Distribution_DistributionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Generation_Distribution_DistributionType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Generation_Distribution_DistributionType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Generation_Distribution_DistributionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Generation_Distribution_DistributionType.Descriptor instead.
func (Generation_Distribution_DistributionType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 1, 0}
}

// *
// Decimal represents an arbitrary-precision decimal number.
type Decimal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * String representation of the decimal number
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Decimal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// *
// Uuid represents a universally unique identifier (UUID).
type Uuid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * String representation of UUID (e.g., "123e4567-e89b-12d3-a456-426614174000")
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uuid) Reset() {
	*x = Uuid{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uuid) ProtoMessage() {}

func (x *Uuid) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uuid.ProtoReflect.Descriptor instead.
func (*Uuid) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Uuid) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// *
// DateTime represents a point in time, independent of any time zone or calendar.
type DateTime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Timestamp in UTC
	Value         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *DateTime) GetValue() *timestamppb.Timestamp {
	if x != nil {
		return x.Value
	}
	return nil
}

// *
// Value is a variant type that can represent different types of values.
// It's used to represent values that can be of multiple types in a type-safe way.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Value_Null
	//	*Value_Int32
	//	*Value_Uint32
	//	*Value_Int64
	//	*Value_Uint64
	//	*Value_Float
	//	*Value_Double
	//	*Value_String_
	//	*Value_Bool
	//	*Value_Decimal
	//	*Value_Uuid
	//	*Value_Datetime
	//	*Value_Struct_
	//	*Value_List_
	Type isValue_Type `protobuf_oneof:"type"`
	// * Field name (used in structs)
	Key           string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetType() isValue_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Value) GetNull() Value_NullValue {
	if x != nil {
		if x, ok := x.Type.(*Value_Null); ok {
			return x.Null
		}
	}
	return Value_NULL_VALUE
}

func (x *Value) GetInt32() int32 {
	if x != nil {
		if x, ok := x.Type.(*Value_Int32); ok {
			return x.Int32
		}
	}
	return 0
}

func (x *Value) GetUint32() uint32 {
	if x != nil {
		if x, ok := x.Type.(*Value_Uint32); ok {
			return x.Uint32
		}
	}
	return 0
}

func (x *Value) GetInt64() int64 {
	if x != nil {
		if x, ok := x.Type.(*Value_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *Value) GetUint64() uint64 {
	if x != nil {
		if x, ok := x.Type.(*Value_Uint64); ok {
			return x.Uint64
		}
	}
	return 0
}

func (x *Value) GetFloat() float32 {
	if x != nil {
		if x, ok := x.Type.(*Value_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *Value) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Type.(*Value_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *Value) GetString_() string {
	if x != nil {
		if x, ok := x.Type.(*Value_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Value) GetBool() bool {
	if x != nil {
		if x, ok := x.Type.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *Value) GetDecimal() *Decimal {
	if x != nil {
		if x, ok := x.Type.(*Value_Decimal); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *Value) GetUuid() *Uuid {
	if x != nil {
		if x, ok := x.Type.(*Value_Uuid); ok {
			return x.Uuid
		}
	}
	return nil
}

func (x *Value) GetDatetime() *DateTime {
	if x != nil {
		if x, ok := x.Type.(*Value_Datetime); ok {
			return x.Datetime
		}
	}
	return nil
}

func (x *Value) GetStruct() *Value_Struct {
	if x != nil {
		if x, ok := x.Type.(*Value_Struct_); ok {
			return x.Struct
		}
	}
	return nil
}

func (x *Value) GetList() *Value_List {
	if x != nil {
		if x, ok := x.Type.(*Value_List_); ok {
			return x.List
		}
	}
	return nil
}

func (x *Value) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type isValue_Type interface {
	isValue_Type()
}

type Value_Null struct {
	// * Null value
	Null Value_NullValue `protobuf:"varint,1,opt,name=null,proto3,enum=stroppy.Value_NullValue,oneof"`
}

type Value_Int32 struct {
	// * 32-bit signed integer
	Int32 int32 `protobuf:"varint,2,opt,name=int32,proto3,oneof"`
}

type Value_Uint32 struct {
	// * 32-bit unsigned integer
	Uint32 uint32 `protobuf:"varint,3,opt,name=uint32,proto3,oneof"`
}

type Value_Int64 struct {
	// * 64-bit signed integer
	Int64 int64 `protobuf:"varint,4,opt,name=int64,proto3,oneof"`
}

type Value_Uint64 struct {
	// * 64-bit unsigned integer
	Uint64 uint64 `protobuf:"varint,5,opt,name=uint64,proto3,oneof"`
}

type Value_Float struct {
	// * 32-bit floating point number
	Float float32 `protobuf:"fixed32,6,opt,name=float,proto3,oneof"`
}

type Value_Double struct {
	// * 64-bit floating point number
	Double float64 `protobuf:"fixed64,7,opt,name=double,proto3,oneof"`
}

type Value_String_ struct {
	// * UTF-8 encoded string
	String_ string `protobuf:"bytes,8,opt,name=string,proto3,oneof"`
}

type Value_Bool struct {
	// * Boolean value
	Bool bool `protobuf:"varint,9,opt,name=bool,proto3,oneof"`
}

type Value_Decimal struct {
	// * Arbitrary-precision decimal
	Decimal *Decimal `protobuf:"bytes,10,opt,name=decimal,proto3,oneof"`
}

type Value_Uuid struct {
	// * Universally unique identifier
	Uuid *Uuid `protobuf:"bytes,11,opt,name=uuid,proto3,oneof"`
}

type Value_Datetime struct {
	// * Date and time
	Datetime *DateTime `protobuf:"bytes,12,opt,name=datetime,proto3,oneof"`
}

type Value_Struct_ struct {
	// * Nested structure
	Struct *Value_Struct `protobuf:"bytes,13,opt,name=struct,proto3,oneof"`
}

type Value_List_ struct {
	// * List of values
	List *Value_List `protobuf:"bytes,14,opt,name=list,proto3,oneof"`
}

func (*Value_Null) isValue_Type() {}

func (*Value_Int32) isValue_Type() {}

func (*Value_Uint32) isValue_Type() {}

func (*Value_Int64) isValue_Type() {}

func (*Value_Uint64) isValue_Type() {}

func (*Value_Float) isValue_Type() {}

func (*Value_Double) isValue_Type() {}

func (*Value_String_) isValue_Type() {}

func (*Value_Bool) isValue_Type() {}

func (*Value_Decimal) isValue_Type() {}

func (*Value_Uuid) isValue_Type() {}

func (*Value_Datetime) isValue_Type() {}

func (*Value_Struct_) isValue_Type() {}

func (*Value_List_) isValue_Type() {}

// *
// Generation contains configuration for generating test data.
// It provides rules and constraints for generating various types of data.
type Generation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type Value_List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * List of values
	Values        []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_List) Reset() {
	*x = Value_List{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_List) ProtoMessage() {}

func (x *Value_List) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_List.ProtoReflect.Descriptor instead.
func (*Value_List) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Value_List) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value_Struct struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Map of field names to values
	Fields        []*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_Struct) Reset() {
	*x = Value_Struct{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Struct) ProtoMessage() {}

func (x *Value_Struct) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Struct.ProtoReflect.Descriptor instead.
func (*Value_Struct) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Value_Struct) GetFields() []*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// *
// Alphabet defines character ranges for string generation.
type Generation_Alphabet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * List of character ranges for this alphabet
	Ranges        []*Generation_Range_UInt32Range `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Alphabet) Reset() {
	*x = Generation_Alphabet{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Alphabet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Alphabet) ProtoMessage() {}

func (x *Generation_Alphabet) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Alphabet.ProtoReflect.Descriptor instead.
func (*Generation_Alphabet) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Generation_Alphabet) GetRanges() []*Generation_Range_UInt32Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// *
// Distribution defines the statistical distribution for value generation.
type Generation_Distribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Type of distribution to use
	Type Generation_Distribution_DistributionType `protobuf:"varint,1,opt,name=type,proto3,enum=stroppy.Generation_Distribution_DistributionType" json:"type,omitempty"`
	// * Distribution parameter (e.g., standard deviation for normal distribution)
	Screw         float64 `protobuf:"fixed64,2,opt,name=screw,proto3" json:"screw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Distribution) Reset() {
	*x = Generation_Distribution{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Distribution) ProtoMessage() {}

func (x *Generation_Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Distribution.ProtoReflect.Descriptor instead.
func (*Generation_Distribution) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Generation_Distribution) GetType() Generation_Distribution_DistributionType {
	if x != nil {
		return x.Type
	}
	return Generation_Distribution_NORMAL
}

func (x *Generation_Distribution) GetScrew() float64 {
	if x != nil {
		return x.Screw
	}
	return 0
}

// *
// Range defines value constraints for generation.
type Generation_Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range) Reset() {
	*x = Generation_Range{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range) ProtoMessage() {}

func (x *Generation_Range) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range.ProtoReflect.Descriptor instead.
func (*Generation_Range) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2}
}

// *
// Rules contains type-specific generation configurations.
type Generation_Rules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules) Reset() {
	*x = Generation_Rules{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules) ProtoMessage() {}

func (x *Generation_Rules) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules.ProtoReflect.Descriptor instead.
func (*Generation_Rules) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3}
}

// *
// Rule defines generation rules for a specific data type.
type Generation_Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Generation_Rule_FloatRules
	//	*Generation_Rule_DoubleRules
	//	*Generation_Rule_Int32Rules
	//	*Generation_Rule_Int64Rules
	//	*Generation_Rule_Uint32Rules
	//	*Generation_Rule_Uint64Rules
	//	*Generation_Rule_BoolRules
	//	*Generation_Rule_StringRules
	//	*Generation_Rule_DatetimeRules
	//	*Generation_Rule_UuidRules
	//	*Generation_Rule_DecimalRules
	Type           isGeneration_Rule_Type   `protobuf_oneof:"type"`
	Distribution   *Generation_Distribution `protobuf:"bytes,1000,opt,name=distribution,proto3,oneof" json:"distribution,omitempty"`
	NullPercentage *uint32                  `protobuf:"varint,1001,opt,name=null_percentage,json=nullPercentage,proto3,oneof" json:"null_percentage,omitempty"`
	Unique         *bool                    `protobuf:"varint,1002,opt,name=unique,proto3,oneof" json:"unique,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Generation_Rule) Reset() {
	*x = Generation_Rule{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rule) ProtoMessage() {}

func (x *Generation_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rule.ProtoReflect.Descriptor instead.
func (*Generation_Rule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 4}
}

func (x *Generation_Rule) GetType() isGeneration_Rule_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Generation_Rule) GetFloatRules() *Generation_Rules_FloatRule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_FloatRules); ok {
			return x.FloatRules
		}
	}
	return nil
}

func (x *Generation_Rule) GetDoubleRules() *Generation_Rules_DoubleRule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_DoubleRules); ok {
			return x.DoubleRules
		}
	}
	return nil
}

func (x *Generation_Rule) GetInt32Rules() *Generation_Rules_Int32Rule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_Int32Rules); ok {
			return x.Int32Rules
		}
	}
	return nil
}

func (x *Generation_Rule) GetInt64Rules() *Generation_Rules_Int64Rule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_Int64Rules); ok {
			return x.Int64Rules
		}
	}
	return nil
}

func (x *Generation_Rule) GetUint32Rules() *Generation_Rules_UInt32Rule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_Uint32Rules); ok {
			return x.Uint32Rules
		}
	}
	return nil
}

func (x *Generation_Rule) GetUint64Rules() *Generation_Rules_UInt64Rule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_Uint64Rules); ok {
			return x.Uint64Rules
		}
	}
	return nil
}

func (x *Generation_Rule) GetBoolRules() *Generation_Rules_BoolRule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_BoolRules); ok {
			return x.BoolRules
		}
	}
	return nil
}

func (x *Generation_Rule) GetStringRules() *Generation_Rules_StringRule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_StringRules); ok {
			return x.StringRules
		}
	}
	return nil
}

func (x *Generation_Rule) GetDatetimeRules() *Generation_Rules_DateTimeRule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_DatetimeRules); ok {
			return x.DatetimeRules
		}
	}
	return nil
}

func (x *Generation_Rule) GetUuidRules() *Generation_Rules_UuidRule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_UuidRules); ok {
			return x.UuidRules
		}
	}
	return nil
}

func (x *Generation_Rule) GetDecimalRules() *Generation_Rules_DecimalRule {
	if x != nil {
		if x, ok := x.Type.(*Generation_Rule_DecimalRules); ok {
			return x.DecimalRules
		}
	}
	return nil
}

func (x *Generation_Rule) GetDistribution() *Generation_Distribution {
	if x != nil {
		return x.Distribution
	}
	return nil
}

func (x *Generation_Rule) GetNullPercentage() uint32 {
	if x != nil && x.NullPercentage != nil {
		return *x.NullPercentage
	}
	return 0
}

func (x *Generation_Rule) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

type isGeneration_Rule_Type interface {
	isGeneration_Rule_Type()
}

type Generation_Rule_FloatRules struct {
	// * Rules for 32-bit floating point numbers
	FloatRules *Generation_Rules_FloatRule `protobuf:"bytes,1,opt,name=float_rules,json=floatRules,proto3,oneof"`
}

type Generation_Rule_DoubleRules struct {
	// * Rules for 64-bit floating point numbers
	DoubleRules *Generation_Rules_DoubleRule `protobuf:"bytes,2,opt,name=double_rules,json=doubleRules,proto3,oneof"`
}

type Generation_Rule_Int32Rules struct {
	// * Rules for 32-bit signed integers
	Int32Rules *Generation_Rules_Int32Rule `protobuf:"bytes,3,opt,name=int32_rules,json=int32Rules,proto3,oneof"`
}

type Generation_Rule_Int64Rules struct {
	// * Rules for 64-bit signed integers
	Int64Rules *Generation_Rules_Int64Rule `protobuf:"bytes,4,opt,name=int64_rules,json=int64Rules,proto3,oneof"`
}

type Generation_Rule_Uint32Rules struct {
	// * Rules for 32-bit unsigned integers
	Uint32Rules *Generation_Rules_UInt32Rule `protobuf:"bytes,5,opt,name=uint32_rules,json=uint32Rules,proto3,oneof"`
}

type Generation_Rule_Uint64Rules struct {
	// * Rules for 64-bit unsigned integers
	Uint64Rules *Generation_Rules_UInt64Rule `protobuf:"bytes,6,opt,name=uint64_rules,json=uint64Rules,proto3,oneof"`
}

type Generation_Rule_BoolRules struct {
	// * Rules for boolean values
	BoolRules *Generation_Rules_BoolRule `protobuf:"bytes,13,opt,name=bool_rules,json=boolRules,proto3,oneof"`
}

type Generation_Rule_StringRules struct {
	// * Rules for string values
	StringRules *Generation_Rules_StringRule `protobuf:"bytes,14,opt,name=string_rules,json=stringRules,proto3,oneof"`
}

type Generation_Rule_DatetimeRules struct {
	// * Rules for date/time values
	DatetimeRules *Generation_Rules_DateTimeRule `protobuf:"bytes,101,opt,name=datetime_rules,json=datetimeRules,proto3,oneof"`
}

type Generation_Rule_UuidRules struct {
	// * Rules for UUIDs
	UuidRules *Generation_Rules_UuidRule `protobuf:"bytes,102,opt,name=uuid_rules,json=uuidRules,proto3,oneof"`
}

type Generation_Rule_DecimalRules struct {
	// * Rules for decimal numbers
	DecimalRules *Generation_Rules_DecimalRule `protobuf:"bytes,103,opt,name=decimal_rules,json=decimalRules,proto3,oneof"`
}

func (*Generation_Rule_FloatRules) isGeneration_Rule_Type() {}

func (*Generation_Rule_DoubleRules) isGeneration_Rule_Type() {}

func (*Generation_Rule_Int32Rules) isGeneration_Rule_Type() {}

func (*Generation_Rule_Int64Rules) isGeneration_Rule_Type() {}

func (*Generation_Rule_Uint32Rules) isGeneration_Rule_Type() {}

func (*Generation_Rule_Uint64Rules) isGeneration_Rule_Type() {}

func (*Generation_Rule_BoolRules) isGeneration_Rule_Type() {}

func (*Generation_Rule_StringRules) isGeneration_Rule_Type() {}

func (*Generation_Rule_DatetimeRules) isGeneration_Rule_Type() {}

func (*Generation_Rule_UuidRules) isGeneration_Rule_Type() {}

func (*Generation_Rule_DecimalRules) isGeneration_Rule_Type() {}

// * Range for string values that can be parsed into other types
type Generation_Range_AnyStringRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min string `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           string `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_AnyStringRange) Reset() {
	*x = Generation_Range_AnyStringRange{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_AnyStringRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_AnyStringRange) ProtoMessage() {}

func (x *Generation_Range_AnyStringRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_AnyStringRange.ProtoReflect.Descriptor instead.
func (*Generation_Range_AnyStringRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 0}
}

func (x *Generation_Range_AnyStringRange) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *Generation_Range_AnyStringRange) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

// * Range for 32-bit floating point numbers
type Generation_Range_FloatRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min float32 `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           float32 `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_FloatRange) Reset() {
	*x = Generation_Range_FloatRange{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_FloatRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_FloatRange) ProtoMessage() {}

func (x *Generation_Range_FloatRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_FloatRange.ProtoReflect.Descriptor instead.
func (*Generation_Range_FloatRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 1}
}

func (x *Generation_Range_FloatRange) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Generation_Range_FloatRange) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// * Range for 64-bit floating point numbers
type Generation_Range_DoubleRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_DoubleRange) Reset() {
	*x = Generation_Range_DoubleRange{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_DoubleRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_DoubleRange) ProtoMessage() {}

func (x *Generation_Range_DoubleRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_DoubleRange.ProtoReflect.Descriptor instead.
func (*Generation_Range_DoubleRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 2}
}

func (x *Generation_Range_DoubleRange) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Generation_Range_DoubleRange) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// * Range for 32-bit signed integers
type Generation_Range_Int32Range struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min int32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           int32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_Int32Range) Reset() {
	*x = Generation_Range_Int32Range{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_Int32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_Int32Range) ProtoMessage() {}

func (x *Generation_Range_Int32Range) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_Int32Range.ProtoReflect.Descriptor instead.
func (*Generation_Range_Int32Range) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 3}
}

func (x *Generation_Range_Int32Range) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Generation_Range_Int32Range) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// * Range for 64-bit signed integers
type Generation_Range_Int64Range struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min int64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           int64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_Int64Range) Reset() {
	*x = Generation_Range_Int64Range{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_Int64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_Int64Range) ProtoMessage() {}

func (x *Generation_Range_Int64Range) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_Int64Range.ProtoReflect.Descriptor instead.
func (*Generation_Range_Int64Range) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 4}
}

func (x *Generation_Range_Int64Range) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Generation_Range_Int64Range) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// * Range for 32-bit unsigned integers
type Generation_Range_UInt32Range struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min uint32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           uint32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_UInt32Range) Reset() {
	*x = Generation_Range_UInt32Range{}
	mi := &file_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_UInt32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_UInt32Range) ProtoMessage() {}

func (x *Generation_Range_UInt32Range) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_UInt32Range.ProtoReflect.Descriptor instead.
func (*Generation_Range_UInt32Range) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 5}
}

func (x *Generation_Range_UInt32Range) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Generation_Range_UInt32Range) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// * Range for 64-bit unsigned integers
type Generation_Range_UInt64Range struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min uint64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           uint64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_UInt64Range) Reset() {
	*x = Generation_Range_UInt64Range{}
	mi := &file_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_UInt64Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_UInt64Range) ProtoMessage() {}

func (x *Generation_Range_UInt64Range) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_UInt64Range.ProtoReflect.Descriptor instead.
func (*Generation_Range_UInt64Range) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 6}
}

func (x *Generation_Range_UInt64Range) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Generation_Range_UInt64Range) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// * Range for decimal numbers
type Generation_Range_DecimalRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Generation_Range_DecimalRange_Default_
	//	*Generation_Range_DecimalRange_Float
	//	*Generation_Range_DecimalRange_Double
	//	*Generation_Range_DecimalRange_String_
	Type          isGeneration_Range_DecimalRange_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_DecimalRange) Reset() {
	*x = Generation_Range_DecimalRange{}
	mi := &file_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_DecimalRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_DecimalRange) ProtoMessage() {}

func (x *Generation_Range_DecimalRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_DecimalRange.ProtoReflect.Descriptor instead.
func (*Generation_Range_DecimalRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 7}
}

func (x *Generation_Range_DecimalRange) GetType() isGeneration_Range_DecimalRange_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Generation_Range_DecimalRange) GetDefault() *Generation_Range_DecimalRange_Default {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DecimalRange_Default_); ok {
			return x.Default
		}
	}
	return nil
}

func (x *Generation_Range_DecimalRange) GetFloat() *Generation_Range_FloatRange {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DecimalRange_Float); ok {
			return x.Float
		}
	}
	return nil
}

func (x *Generation_Range_DecimalRange) GetDouble() *Generation_Range_DoubleRange {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DecimalRange_Double); ok {
			return x.Double
		}
	}
	return nil
}

func (x *Generation_Range_DecimalRange) GetString_() *Generation_Range_AnyStringRange {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DecimalRange_String_); ok {
			return x.String_
		}
	}
	return nil
}

type isGeneration_Range_DecimalRange_Type interface {
	isGeneration_Range_DecimalRange_Type()
}

type Generation_Range_DecimalRange_Default_ struct {
	// * Exact decimal range
	Default *Generation_Range_DecimalRange_Default `protobuf:"bytes,1,opt,name=default,proto3,oneof"`
}

type Generation_Range_DecimalRange_Float struct {
	// * Float-based range
	Float *Generation_Range_FloatRange `protobuf:"bytes,2,opt,name=float,proto3,oneof"`
}

type Generation_Range_DecimalRange_Double struct {
	// * Double-based range
	Double *Generation_Range_DoubleRange `protobuf:"bytes,3,opt,name=double,proto3,oneof"`
}

type Generation_Range_DecimalRange_String_ struct {
	// * String-based range (supports scientific notation)
	String_ *Generation_Range_AnyStringRange `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

func (*Generation_Range_DecimalRange_Default_) isGeneration_Range_DecimalRange_Type() {}

func (*Generation_Range_DecimalRange_Float) isGeneration_Range_DecimalRange_Type() {}

func (*Generation_Range_DecimalRange_Double) isGeneration_Range_DecimalRange_Type() {}

func (*Generation_Range_DecimalRange_String_) isGeneration_Range_DecimalRange_Type() {}

// * Range for date/time values
type Generation_Range_DateTimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Generation_Range_DateTimeRange_Default_
	//	*Generation_Range_DateTimeRange_String_
	//	*Generation_Range_DateTimeRange_TimestampPb_
	//	*Generation_Range_DateTimeRange_Timestamp_
	Type          isGeneration_Range_DateTimeRange_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_DateTimeRange) Reset() {
	*x = Generation_Range_DateTimeRange{}
	mi := &file_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_DateTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_DateTimeRange) ProtoMessage() {}

func (x *Generation_Range_DateTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_DateTimeRange.ProtoReflect.Descriptor instead.
func (*Generation_Range_DateTimeRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 8}
}

func (x *Generation_Range_DateTimeRange) GetType() isGeneration_Range_DateTimeRange_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Generation_Range_DateTimeRange) GetDefault() *Generation_Range_DateTimeRange_Default {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DateTimeRange_Default_); ok {
			return x.Default
		}
	}
	return nil
}

func (x *Generation_Range_DateTimeRange) GetString_() *Generation_Range_AnyStringRange {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DateTimeRange_String_); ok {
			return x.String_
		}
	}
	return nil
}

func (x *Generation_Range_DateTimeRange) GetTimestampPb() *Generation_Range_DateTimeRange_TimestampPb {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DateTimeRange_TimestampPb_); ok {
			return x.TimestampPb
		}
	}
	return nil
}

func (x *Generation_Range_DateTimeRange) GetTimestamp() *Generation_Range_DateTimeRange_Timestamp {
	if x != nil {
		if x, ok := x.Type.(*Generation_Range_DateTimeRange_Timestamp_); ok {
			return x.Timestamp
		}
	}
	return nil
}

type isGeneration_Range_DateTimeRange_Type interface {
	isGeneration_Range_DateTimeRange_Type()
}

type Generation_Range_DateTimeRange_Default_ struct {
	// * Exact date/time range
	Default *Generation_Range_DateTimeRange_Default `protobuf:"bytes,1,opt,name=default,proto3,oneof"`
}

type Generation_Range_DateTimeRange_String_ struct {
	// * String-based range (ISO 8601 format)
	String_ *Generation_Range_AnyStringRange `protobuf:"bytes,2,opt,name=string,proto3,oneof"`
}

type Generation_Range_DateTimeRange_TimestampPb_ struct {
	// * Protocol Buffers timestamp range
	TimestampPb *Generation_Range_DateTimeRange_TimestampPb `protobuf:"bytes,3,opt,name=timestamp_pb,json=timestampPb,proto3,oneof"`
}

type Generation_Range_DateTimeRange_Timestamp_ struct {
	// * Unix timestamp range
	Timestamp *Generation_Range_DateTimeRange_Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3,oneof"`
}

func (*Generation_Range_DateTimeRange_Default_) isGeneration_Range_DateTimeRange_Type() {}

func (*Generation_Range_DateTimeRange_String_) isGeneration_Range_DateTimeRange_Type() {}

func (*Generation_Range_DateTimeRange_TimestampPb_) isGeneration_Range_DateTimeRange_Type() {}

func (*Generation_Range_DateTimeRange_Timestamp_) isGeneration_Range_DateTimeRange_Type() {}

// * Default decimal range
type Generation_Range_DecimalRange_Default struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum value (inclusive)
	Min *Decimal `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum value (inclusive)
	Max           *Decimal `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_DecimalRange_Default) Reset() {
	*x = Generation_Range_DecimalRange_Default{}
	mi := &file_common_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_DecimalRange_Default) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_DecimalRange_Default) ProtoMessage() {}

func (x *Generation_Range_DecimalRange_Default) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_DecimalRange_Default.ProtoReflect.Descriptor instead.
func (*Generation_Range_DecimalRange_Default) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 7, 0}
}

func (x *Generation_Range_DecimalRange_Default) GetMin() *Decimal {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Generation_Range_DecimalRange_Default) GetMax() *Decimal {
	if x != nil {
		return x.Max
	}
	return nil
}

// * Default date/time range
type Generation_Range_DateTimeRange_Default struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum timestamp (inclusive)
	Min *DateTime `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum timestamp (inclusive)
	Max           *DateTime `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_DateTimeRange_Default) Reset() {
	*x = Generation_Range_DateTimeRange_Default{}
	mi := &file_common_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_DateTimeRange_Default) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_DateTimeRange_Default) ProtoMessage() {}

func (x *Generation_Range_DateTimeRange_Default) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_DateTimeRange_Default.ProtoReflect.Descriptor instead.
func (*Generation_Range_DateTimeRange_Default) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 8, 0}
}

func (x *Generation_Range_DateTimeRange_Default) GetMin() *DateTime {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Generation_Range_DateTimeRange_Default) GetMax() *DateTime {
	if x != nil {
		return x.Max
	}
	return nil
}

// * Protocol Buffers timestamp range
type Generation_Range_DateTimeRange_TimestampPb struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum timestamp (inclusive)
	Min *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum timestamp (inclusive)
	Max           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_DateTimeRange_TimestampPb) Reset() {
	*x = Generation_Range_DateTimeRange_TimestampPb{}
	mi := &file_common_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_DateTimeRange_TimestampPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_DateTimeRange_TimestampPb) ProtoMessage() {}

func (x *Generation_Range_DateTimeRange_TimestampPb) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_DateTimeRange_TimestampPb.ProtoReflect.Descriptor instead.
func (*Generation_Range_DateTimeRange_TimestampPb) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 8, 1}
}

func (x *Generation_Range_DateTimeRange_TimestampPb) GetMin() *timestamppb.Timestamp {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *Generation_Range_DateTimeRange_TimestampPb) GetMax() *timestamppb.Timestamp {
	if x != nil {
		return x.Max
	}
	return nil
}

// * Unix timestamp range
type Generation_Range_DateTimeRange_Timestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum Unix timestamp (inclusive)
	Min uint32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// * Maximum Unix timestamp (inclusive)
	Max           uint32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Range_DateTimeRange_Timestamp) Reset() {
	*x = Generation_Range_DateTimeRange_Timestamp{}
	mi := &file_common_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Range_DateTimeRange_Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Range_DateTimeRange_Timestamp) ProtoMessage() {}

func (x *Generation_Range_DateTimeRange_Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Range_DateTimeRange_Timestamp.ProtoReflect.Descriptor instead.
func (*Generation_Range_DateTimeRange_Timestamp) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 2, 8, 2}
}

func (x *Generation_Range_DateTimeRange_Timestamp) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Generation_Range_DateTimeRange_Timestamp) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// * Rules for generating 32-bit floating point numbers
type Generation_Rules_FloatRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid value range
	Range *Generation_Range_FloatRange `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *float32 `protobuf:"fixed32,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_FloatRule) Reset() {
	*x = Generation_Rules_FloatRule{}
	mi := &file_common_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_FloatRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_FloatRule) ProtoMessage() {}

func (x *Generation_Rules_FloatRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_FloatRule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_FloatRule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 0}
}

func (x *Generation_Rules_FloatRule) GetRange() *Generation_Range_FloatRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_FloatRule) GetConstant() float32 {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return 0
}

// * Rules for generating 64-bit floating point numbers
type Generation_Rules_DoubleRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid value range
	Range *Generation_Range_DoubleRange `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *float64 `protobuf:"fixed64,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_DoubleRule) Reset() {
	*x = Generation_Rules_DoubleRule{}
	mi := &file_common_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_DoubleRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_DoubleRule) ProtoMessage() {}

func (x *Generation_Rules_DoubleRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_DoubleRule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_DoubleRule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 1}
}

func (x *Generation_Rules_DoubleRule) GetRange() *Generation_Range_DoubleRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_DoubleRule) GetConstant() float64 {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return 0
}

// * Rules for generating 32-bit signed integers
type Generation_Rules_Int32Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid value range
	Range *Generation_Range_Int32Range `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *int32 `protobuf:"varint,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_Int32Rule) Reset() {
	*x = Generation_Rules_Int32Rule{}
	mi := &file_common_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_Int32Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_Int32Rule) ProtoMessage() {}

func (x *Generation_Rules_Int32Rule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_Int32Rule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_Int32Rule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 2}
}

func (x *Generation_Rules_Int32Rule) GetRange() *Generation_Range_Int32Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_Int32Rule) GetConstant() int32 {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return 0
}

// * Rules for generating 64-bit signed integers
type Generation_Rules_Int64Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid value range
	Range *Generation_Range_Int64Range `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *int64 `protobuf:"varint,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_Int64Rule) Reset() {
	*x = Generation_Rules_Int64Rule{}
	mi := &file_common_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_Int64Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_Int64Rule) ProtoMessage() {}

func (x *Generation_Rules_Int64Rule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_Int64Rule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_Int64Rule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 3}
}

func (x *Generation_Rules_Int64Rule) GetRange() *Generation_Range_Int64Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_Int64Rule) GetConstant() int64 {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return 0
}

// * Rules for generating 32-bit unsigned integers
type Generation_Rules_UInt32Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid value range
	Range *Generation_Range_UInt32Range `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *uint32 `protobuf:"varint,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_UInt32Rule) Reset() {
	*x = Generation_Rules_UInt32Rule{}
	mi := &file_common_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_UInt32Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_UInt32Rule) ProtoMessage() {}

func (x *Generation_Rules_UInt32Rule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_UInt32Rule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_UInt32Rule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 4}
}

func (x *Generation_Rules_UInt32Rule) GetRange() *Generation_Range_UInt32Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_UInt32Rule) GetConstant() uint32 {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return 0
}

// * Rules for generating 64-bit unsigned integers
type Generation_Rules_UInt64Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid value range
	Range *Generation_Range_UInt64Range `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *uint64 `protobuf:"varint,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_UInt64Rule) Reset() {
	*x = Generation_Rules_UInt64Rule{}
	mi := &file_common_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_UInt64Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_UInt64Rule) ProtoMessage() {}

func (x *Generation_Rules_UInt64Rule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_UInt64Rule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_UInt64Rule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 5}
}

func (x *Generation_Rules_UInt64Rule) GetRange() *Generation_Range_UInt64Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_UInt64Rule) GetConstant() uint64 {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return 0
}

// * Rules for generating boolean values
type Generation_Rules_BoolRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Fixed value (if not specified, generates random booleans)
	Constant      *bool `protobuf:"varint,1,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_BoolRule) Reset() {
	*x = Generation_Rules_BoolRule{}
	mi := &file_common_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_BoolRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_BoolRule) ProtoMessage() {}

func (x *Generation_Rules_BoolRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_BoolRule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_BoolRule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 6}
}

func (x *Generation_Rules_BoolRule) GetConstant() bool {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return false
}

// * Rules for generating string values
type Generation_Rules_StringRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Character set to use for generation
	Alphabet *Generation_Alphabet `protobuf:"bytes,1,opt,name=alphabet,proto3,oneof" json:"alphabet,omitempty"`
	// * Valid length range for the string
	LenRange *Generation_Range_UInt64Range `protobuf:"bytes,2,opt,name=len_range,json=lenRange,proto3" json:"len_range,omitempty"`
	// * Fixed value (if specified, overrides generation)
	Constant      *string `protobuf:"bytes,3,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_StringRule) Reset() {
	*x = Generation_Rules_StringRule{}
	mi := &file_common_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_StringRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_StringRule) ProtoMessage() {}

func (x *Generation_Rules_StringRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_StringRule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_StringRule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 7}
}

func (x *Generation_Rules_StringRule) GetAlphabet() *Generation_Alphabet {
	if x != nil {
		return x.Alphabet
	}
	return nil
}

func (x *Generation_Rules_StringRule) GetLenRange() *Generation_Range_UInt64Range {
	if x != nil {
		return x.LenRange
	}
	return nil
}

func (x *Generation_Rules_StringRule) GetConstant() string {
	if x != nil && x.Constant != nil {
		return *x.Constant
	}
	return ""
}

// * Rules for generating date/time values
type Generation_Rules_DateTimeRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid time range
	Range *Generation_Range_DateTimeRange `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *DateTime `protobuf:"bytes,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_DateTimeRule) Reset() {
	*x = Generation_Rules_DateTimeRule{}
	mi := &file_common_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_DateTimeRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_DateTimeRule) ProtoMessage() {}

func (x *Generation_Rules_DateTimeRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_DateTimeRule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_DateTimeRule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 8}
}

func (x *Generation_Rules_DateTimeRule) GetRange() *Generation_Range_DateTimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_DateTimeRule) GetConstant() *DateTime {
	if x != nil {
		return x.Constant
	}
	return nil
}

// * Rules for generating UUIDs
type Generation_Rules_UuidRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Fixed UUID (if not specified, generates random UUIDs)
	Constant      *Uuid `protobuf:"bytes,1,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_UuidRule) Reset() {
	*x = Generation_Rules_UuidRule{}
	mi := &file_common_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_UuidRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_UuidRule) ProtoMessage() {}

func (x *Generation_Rules_UuidRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_UuidRule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_UuidRule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 9}
}

func (x *Generation_Rules_UuidRule) GetConstant() *Uuid {
	if x != nil {
		return x.Constant
	}
	return nil
}

// * Rules for generating decimal numbers
type Generation_Rules_DecimalRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Valid value range
	Range *Generation_Range_DecimalRange `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// * Fixed value (if specified, overrides range)
	Constant      *Decimal `protobuf:"bytes,2,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation_Rules_DecimalRule) Reset() {
	*x = Generation_Rules_DecimalRule{}
	mi := &file_common_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation_Rules_DecimalRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation_Rules_DecimalRule) ProtoMessage() {}

func (x *Generation_Rules_DecimalRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation_Rules_DecimalRule.ProtoReflect.Descriptor instead.
func (*Generation_Rules_DecimalRule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4, 3, 10}
}

func (x *Generation_Rules_DecimalRule) GetRange() *Generation_Range_DecimalRange {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Generation_Rules_DecimalRule) GetConstant() *Decimal {
	if x != nil {
		return x.Constant
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\astroppy\x1a\x1bgen/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\aDecimal\x12\x1d\n" +
	"\x05value\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05value\"&\n" +
	"\x04Uuid\x12\x1e\n" +
	"\x05value\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x05value\"<\n" +
	"\bDateTime\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05value\"\xf6\x04\n" +
	"\x05Value\x12.\n" +
	"\x04null\x18\x01 \x01(\x0e2\x18.stroppy.Value.NullValueH\x00R\x04null\x12\x16\n" +
	"\x05int32\x18\x02 \x01(\x05H\x00R\x05int32\x12\x18\n" +
	"\x06uint32\x18\x03 \x01(\rH\x00R\x06uint32\x12\x16\n" +
	"\x05int64\x18\x04 \x01(\x03H\x00R\x05int64\x12\x18\n" +
	"\x06uint64\x18\x05 \x01(\x04H\x00R\x06uint64\x12\x16\n" +
	"\x05float\x18\x06 \x01(\x02H\x00R\x05float\x12\x18\n" +
	"\x06double\x18\a \x01(\x01H\x00R\x06double\x12\x18\n" +
	"\x06string\x18\b \x01(\tH\x00R\x06string\x12\x14\n" +
	"\x04bool\x18\t \x01(\bH\x00R\x04bool\x12,\n" +
	"\adecimal\x18\n" +
	" \x01(\v2\x10.stroppy.DecimalH\x00R\adecimal\x12#\n" +
	"\x04uuid\x18\v \x01(\v2\r.stroppy.UuidH\x00R\x04uuid\x12/\n" +
	"\bdatetime\x18\f \x01(\v2\x11.stroppy.DateTimeH\x00R\bdatetime\x12/\n" +
	"\x06struct\x18\r \x01(\v2\x15.stroppy.Value.StructH\x00R\x06struct\x12)\n" +
	"\x04list\x18\x0e \x01(\v2\x13.stroppy.Value.ListH\x00R\x04list\x12\x10\n" +
	"\x03key\x18e \x01(\tR\x03key\x1a.\n" +
	"\x04List\x12&\n" +
	"\x06values\x18\x01 \x03(\v2\x0e.stroppy.ValueR\x06values\x1a0\n" +
	"\x06Struct\x12&\n" +
	"\x06fields\x18\x01 \x03(\v2\x0e.stroppy.ValueR\x06fields\"\x1b\n" +
	"\tNullValue\x12\x0e\n" +
	"\n" +
	"NULL_VALUE\x10\x00B\x06\n" +
	"\x04type\"\x9f \n" +
	"\n" +
	"Generation\x1aZ\n" +
	"\bAlphabet\x12N\n" +
	"\x06ranges\x18\x01 \x03(\v2%.stroppy.Generation.Range.UInt32RangeB\x0f\xfaB\f\x92\x01\t\b\x01\"\x05\x8a\x01\x02\x10\x01R\x06ranges\x1a\xbc\x01\n" +
	"\fDistribution\x12O\n" +
	"\x04type\x18\x01 \x01(\x0e21.stroppy.Generation.Distribution.DistributionTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x12$\n" +
	"\x05screw\x18\x02 \x01(\x01B\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x05screw\"5\n" +
	"\x10DistributionType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\v\n" +
	"\aUNIFORM\x10\x01\x12\b\n" +
	"\x04ZIPF\x10\x02\x1a\xba\n" +
	"\n" +
	"\x05Range\x1a4\n" +
	"\x0eAnyStringRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\tR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\tR\x03max\x1a0\n" +
	"\n" +
	"FloatRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x02R\x03max\x1a1\n" +
	"\vDoubleRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x1a0\n" +
	"\n" +
	"Int32Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x1a0\n" +
	"\n" +
	"Int64Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x03R\x03max\x1a1\n" +
	"\vUInt32Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03max\x1a1\n" +
	"\vUInt64Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x04R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x04R\x03max\x1a\xfd\x02\n" +
	"\fDecimalRange\x12J\n" +
	"\adefault\x18\x01 \x01(\v2..stroppy.Generation.Range.DecimalRange.DefaultH\x00R\adefault\x12<\n" +
	"\x05float\x18\x02 \x01(\v2$.stroppy.Generation.Range.FloatRangeH\x00R\x05float\x12?\n" +
	"\x06double\x18\x03 \x01(\v2%.stroppy.Generation.Range.DoubleRangeH\x00R\x06double\x12B\n" +
	"\x06string\x18\x04 \x01(\v2(.stroppy.Generation.Range.AnyStringRangeH\x00R\x06string\x1aQ\n" +
	"\aDefault\x12\"\n" +
	"\x03min\x18\x01 \x01(\v2\x10.stroppy.DecimalR\x03min\x12\"\n" +
	"\x03max\x18\x02 \x01(\v2\x10.stroppy.DecimalR\x03maxB\v\n" +
	"\x04type\x12\x03\xf8B\x01\x1a\xcb\x04\n" +
	"\rDateTimeRange\x12K\n" +
	"\adefault\x18\x01 \x01(\v2/.stroppy.Generation.Range.DateTimeRange.DefaultH\x00R\adefault\x12B\n" +
	"\x06string\x18\x02 \x01(\v2(.stroppy.Generation.Range.AnyStringRangeH\x00R\x06string\x12X\n" +
	"\ftimestamp_pb\x18\x03 \x01(\v23.stroppy.Generation.Range.DateTimeRange.TimestampPbH\x00R\vtimestampPb\x12Q\n" +
	"\ttimestamp\x18\x04 \x01(\v21.stroppy.Generation.Range.DateTimeRange.TimestampH\x00R\ttimestamp\x1aS\n" +
	"\aDefault\x12#\n" +
	"\x03min\x18\x01 \x01(\v2\x11.stroppy.DateTimeR\x03min\x12#\n" +
	"\x03max\x18\x02 \x01(\v2\x11.stroppy.DateTimeR\x03max\x1ai\n" +
	"\vTimestampPb\x12,\n" +
	"\x03min\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03min\x12,\n" +
	"\x03max\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03max\x1a/\n" +
	"\tTimestamp\x12\x10\n" +
	"\x03min\x18\x01 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03maxB\v\n" +
	"\x04type\x12\x03\xf8B\x01\x1a\xa3\v\n" +
	"\x05Rules\x1a\x7f\n" +
	"\tFloatRule\x12D\n" +
	"\x05range\x18\x01 \x01(\v2$.stroppy.Generation.Range.FloatRangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x12\x1f\n" +
	"\bconstant\x18\x02 \x01(\x02H\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\x81\x01\n" +
	"\n" +
	"DoubleRule\x12E\n" +
	"\x05range\x18\x01 \x01(\v2%.stroppy.Generation.Range.DoubleRangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x12\x1f\n" +
	"\bconstant\x18\x02 \x01(\x01H\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\x7f\n" +
	"\tInt32Rule\x12D\n" +
	"\x05range\x18\x01 \x01(\v2$.stroppy.Generation.Range.Int32RangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x12\x1f\n" +
	"\bconstant\x18\x02 \x01(\x05H\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\x7f\n" +
	"\tInt64Rule\x12D\n" +
	"\x05range\x18\x01 \x01(\v2$.stroppy.Generation.Range.Int64RangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x12\x1f\n" +
	"\bconstant\x18\x02 \x01(\x03H\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\x81\x01\n" +
	"\n" +
	"UInt32Rule\x12E\n" +
	"\x05range\x18\x01 \x01(\v2%.stroppy.Generation.Range.UInt32RangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x12\x1f\n" +
	"\bconstant\x18\x02 \x01(\rH\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\x81\x01\n" +
	"\n" +
	"UInt64Rule\x12E\n" +
	"\x05range\x18\x01 \x01(\v2%.stroppy.Generation.Range.UInt64RangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x12\x1f\n" +
	"\bconstant\x18\x02 \x01(\x04H\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a8\n" +
	"\bBoolRule\x12\x1f\n" +
	"\bconstant\x18\x01 \x01(\bH\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\xd4\x01\n" +
	"\n" +
	"StringRule\x12=\n" +
	"\balphabet\x18\x01 \x01(\v2\x1c.stroppy.Generation.AlphabetH\x00R\balphabet\x88\x01\x01\x12L\n" +
	"\tlen_range\x18\x02 \x01(\v2%.stroppy.Generation.Range.UInt64RangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\blenRange\x12\x1f\n" +
	"\bconstant\x18\x03 \x01(\tH\x01R\bconstant\x88\x01\x01B\v\n" +
	"\t_alphabetB\v\n" +
	"\t_constant\x1a\x98\x01\n" +
	"\fDateTimeRule\x12G\n" +
	"\x05range\x18\x01 \x01(\v2'.stroppy.Generation.Range.DateTimeRangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x122\n" +
	"\bconstant\x18\x02 \x01(\v2\x11.stroppy.DateTimeH\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1aG\n" +
	"\bUuidRule\x12.\n" +
	"\bconstant\x18\x01 \x01(\v2\r.stroppy.UuidH\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\x95\x01\n" +
	"\vDecimalRule\x12F\n" +
	"\x05range\x18\x01 \x01(\v2&.stroppy.Generation.Range.DecimalRangeB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05range\x121\n" +
	"\bconstant\x18\x02 \x01(\v2\x10.stroppy.DecimalH\x00R\bconstant\x88\x01\x01B\v\n" +
	"\t_constant\x1a\x92\b\n" +
	"\x04Rule\x12F\n" +
	"\vfloat_rules\x18\x01 \x01(\v2#.stroppy.Generation.Rules.FloatRuleH\x00R\n" +
	"floatRules\x12I\n" +
	"\fdouble_rules\x18\x02 \x01(\v2$.stroppy.Generation.Rules.DoubleRuleH\x00R\vdoubleRules\x12F\n" +
	"\vint32_rules\x18\x03 \x01(\v2#.stroppy.Generation.Rules.Int32RuleH\x00R\n" +
	"int32Rules\x12F\n" +
	"\vint64_rules\x18\x04 \x01(\v2#.stroppy.Generation.Rules.Int64RuleH\x00R\n" +
	"int64Rules\x12I\n" +
	"\fuint32_rules\x18\x05 \x01(\v2$.stroppy.Generation.Rules.UInt32RuleH\x00R\vuint32Rules\x12I\n" +
	"\fuint64_rules\x18\x06 \x01(\v2$.stroppy.Generation.Rules.UInt64RuleH\x00R\vuint64Rules\x12C\n" +
	"\n" +
	"bool_rules\x18\r \x01(\v2\".stroppy.Generation.Rules.BoolRuleH\x00R\tboolRules\x12I\n" +
	"\fstring_rules\x18\x0e \x01(\v2$.stroppy.Generation.Rules.StringRuleH\x00R\vstringRules\x12O\n" +
	"\x0edatetime_rules\x18e \x01(\v2&.stroppy.Generation.Rules.DateTimeRuleH\x00R\rdatetimeRules\x12C\n" +
	"\n" +
	"uuid_rules\x18f \x01(\v2\".stroppy.Generation.Rules.UuidRuleH\x00R\tuuidRules\x12L\n" +
	"\rdecimal_rules\x18g \x01(\v2%.stroppy.Generation.Rules.DecimalRuleH\x00R\fdecimalRules\x12J\n" +
	"\fdistribution\x18\xe8\a \x01(\v2 .stroppy.Generation.DistributionH\x01R\fdistribution\x88\x01\x01\x126\n" +
	"\x0fnull_percentage\x18\xe9\a \x01(\rB\a\xfaB\x04*\x02 \x00H\x02R\x0enullPercentage\x88\x01\x01\x12\x1c\n" +
	"\x06unique\x18\xea\a \x01(\bH\x03R\x06unique\x88\x01\x01B\v\n" +
	"\x04type\x12\x03\xf8B\x01B\x0f\n" +
	"\r_distributionB\x12\n" +
	"\x10_null_percentageB\t\n" +
	"\a_uniqueB.Z,github.com/stroppy-io/stroppy-core/pkg/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_common_proto_goTypes = []any{
	(Value_NullValue)(0),                               // 0: stroppy.Value.NullValue
	(Generation_Distribution_DistributionType)(0),      // 1: stroppy.Generation.Distribution.DistributionType
	(*Decimal)(nil),                                    // 2: stroppy.Decimal
	(*Uuid)(nil),                                       // 3: stroppy.Uuid
	(*DateTime)(nil),                                   // 4: stroppy.DateTime
	(*Value)(nil),                                      // 5: stroppy.Value
	(*Generation)(nil),                                 // 6: stroppy.Generation
	(*Value_List)(nil),                                 // 7: stroppy.Value.List
	(*Value_Struct)(nil),                               // 8: stroppy.Value.Struct
	(*Generation_Alphabet)(nil),                        // 9: stroppy.Generation.Alphabet
	(*Generation_Distribution)(nil),                    // 10: stroppy.Generation.Distribution
	(*Generation_Range)(nil),                           // 11: stroppy.Generation.Range
	(*Generation_Rules)(nil),                           // 12: stroppy.Generation.Rules
	(*Generation_Rule)(nil),                            // 13: stroppy.Generation.Rule
	(*Generation_Range_AnyStringRange)(nil),            // 14: stroppy.Generation.Range.AnyStringRange
	(*Generation_Range_FloatRange)(nil),                // 15: stroppy.Generation.Range.FloatRange
	(*Generation_Range_DoubleRange)(nil),               // 16: stroppy.Generation.Range.DoubleRange
	(*Generation_Range_Int32Range)(nil),                // 17: stroppy.Generation.Range.Int32Range
	(*Generation_Range_Int64Range)(nil),                // 18: stroppy.Generation.Range.Int64Range
	(*Generation_Range_UInt32Range)(nil),               // 19: stroppy.Generation.Range.UInt32Range
	(*Generation_Range_UInt64Range)(nil),               // 20: stroppy.Generation.Range.UInt64Range
	(*Generation_Range_DecimalRange)(nil),              // 21: stroppy.Generation.Range.DecimalRange
	(*Generation_Range_DateTimeRange)(nil),             // 22: stroppy.Generation.Range.DateTimeRange
	(*Generation_Range_DecimalRange_Default)(nil),      // 23: stroppy.Generation.Range.DecimalRange.Default
	(*Generation_Range_DateTimeRange_Default)(nil),     // 24: stroppy.Generation.Range.DateTimeRange.Default
	(*Generation_Range_DateTimeRange_TimestampPb)(nil), // 25: stroppy.Generation.Range.DateTimeRange.TimestampPb
	(*Generation_Range_DateTimeRange_Timestamp)(nil),   // 26: stroppy.Generation.Range.DateTimeRange.Timestamp
	(*Generation_Rules_FloatRule)(nil),                 // 27: stroppy.Generation.Rules.FloatRule
	(*Generation_Rules_DoubleRule)(nil),                // 28: stroppy.Generation.Rules.DoubleRule
	(*Generation_Rules_Int32Rule)(nil),                 // 29: stroppy.Generation.Rules.Int32Rule
	(*Generation_Rules_Int64Rule)(nil),                 // 30: stroppy.Generation.Rules.Int64Rule
	(*Generation_Rules_UInt32Rule)(nil),                // 31: stroppy.Generation.Rules.UInt32Rule
	(*Generation_Rules_UInt64Rule)(nil),                // 32: stroppy.Generation.Rules.UInt64Rule
	(*Generation_Rules_BoolRule)(nil),                  // 33: stroppy.Generation.Rules.BoolRule
	(*Generation_Rules_StringRule)(nil),                // 34: stroppy.Generation.Rules.StringRule
	(*Generation_Rules_DateTimeRule)(nil),              // 35: stroppy.Generation.Rules.DateTimeRule
	(*Generation_Rules_UuidRule)(nil),                  // 36: stroppy.Generation.Rules.UuidRule
	(*Generation_Rules_DecimalRule)(nil),               // 37: stroppy.Generation.Rules.DecimalRule
	(*timestamppb.Timestamp)(nil),                      // 38: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	38, // 0: stroppy.DateTime.value:type_name -> google.protobuf.Timestamp
	0,  // 1: stroppy.Value.null:type_name -> stroppy.Value.NullValue
	2,  // 2: stroppy.Value.decimal:type_name -> stroppy.Decimal
	3,  // 3: stroppy.Value.uuid:type_name -> stroppy.Uuid
	4,  // 4: stroppy.Value.datetime:type_name -> stroppy.DateTime
	8,  // 5: stroppy.Value.struct:type_name -> stroppy.Value.Struct
	7,  // 6: stroppy.Value.list:type_name -> stroppy.Value.List
	5,  // 7: stroppy.Value.List.values:type_name -> stroppy.Value
	5,  // 8: stroppy.Value.Struct.fields:type_name -> stroppy.Value
	19, // 9: stroppy.Generation.Alphabet.ranges:type_name -> stroppy.Generation.Range.UInt32Range
	1,  // 10: stroppy.Generation.Distribution.type:type_name -> stroppy.Generation.Distribution.DistributionType
	27, // 11: stroppy.Generation.Rule.float_rules:type_name -> stroppy.Generation.Rules.FloatRule
	28, // 12: stroppy.Generation.Rule.double_rules:type_name -> stroppy.Generation.Rules.DoubleRule
	29, // 13: stroppy.Generation.Rule.int32_rules:type_name -> stroppy.Generation.Rules.Int32Rule
	30, // 14: stroppy.Generation.Rule.int64_rules:type_name -> stroppy.Generation.Rules.Int64Rule
	31, // 15: stroppy.Generation.Rule.uint32_rules:type_name -> stroppy.Generation.Rules.UInt32Rule
	32, // 16: stroppy.Generation.Rule.uint64_rules:type_name -> stroppy.Generation.Rules.UInt64Rule
	33, // 17: stroppy.Generation.Rule.bool_rules:type_name -> stroppy.Generation.Rules.BoolRule
	34, // 18: stroppy.Generation.Rule.string_rules:type_name -> stroppy.Generation.Rules.StringRule
	35, // 19: stroppy.Generation.Rule.datetime_rules:type_name -> stroppy.Generation.Rules.DateTimeRule
	36, // 20: stroppy.Generation.Rule.uuid_rules:type_name -> stroppy.Generation.Rules.UuidRule
	37, // 21: stroppy.Generation.Rule.decimal_rules:type_name -> stroppy.Generation.Rules.DecimalRule
	10, // 22: stroppy.Generation.Rule.distribution:type_name -> stroppy.Generation.Distribution
	23, // 23: stroppy.Generation.Range.DecimalRange.default:type_name -> stroppy.Generation.Range.DecimalRange.Default
	15, // 24: stroppy.Generation.Range.DecimalRange.float:type_name -> stroppy.Generation.Range.FloatRange
	16, // 25: stroppy.Generation.Range.DecimalRange.double:type_name -> stroppy.Generation.Range.DoubleRange
	14, // 26: stroppy.Generation.Range.DecimalRange.string:type_name -> stroppy.Generation.Range.AnyStringRange
	24, // 27: stroppy.Generation.Range.DateTimeRange.default:type_name -> stroppy.Generation.Range.DateTimeRange.Default
	14, // 28: stroppy.Generation.Range.DateTimeRange.string:type_name -> stroppy.Generation.Range.AnyStringRange
	25, // 29: stroppy.Generation.Range.DateTimeRange.timestamp_pb:type_name -> stroppy.Generation.Range.DateTimeRange.TimestampPb
	26, // 30: stroppy.Generation.Range.DateTimeRange.timestamp:type_name -> stroppy.Generation.Range.DateTimeRange.Timestamp
	2,  // 31: stroppy.Generation.Range.DecimalRange.Default.min:type_name -> stroppy.Decimal
	2,  // 32: stroppy.Generation.Range.DecimalRange.Default.max:type_name -> stroppy.Decimal
	4,  // 33: stroppy.Generation.Range.DateTimeRange.Default.min:type_name -> stroppy.DateTime
	4,  // 34: stroppy.Generation.Range.DateTimeRange.Default.max:type_name -> stroppy.DateTime
	38, // 35: stroppy.Generation.Range.DateTimeRange.TimestampPb.min:type_name -> google.protobuf.Timestamp
	38, // 36: stroppy.Generation.Range.DateTimeRange.TimestampPb.max:type_name -> google.protobuf.Timestamp
	15, // 37: stroppy.Generation.Rules.FloatRule.range:type_name -> stroppy.Generation.Range.FloatRange
	16, // 38: stroppy.Generation.Rules.DoubleRule.range:type_name -> stroppy.Generation.Range.DoubleRange
	17, // 39: stroppy.Generation.Rules.Int32Rule.range:type_name -> stroppy.Generation.Range.Int32Range
	18, // 40: stroppy.Generation.Rules.Int64Rule.range:type_name -> stroppy.Generation.Range.Int64Range
	19, // 41: stroppy.Generation.Rules.UInt32Rule.range:type_name -> stroppy.Generation.Range.UInt32Range
	20, // 42: stroppy.Generation.Rules.UInt64Rule.range:type_name -> stroppy.Generation.Range.UInt64Range
	9,  // 43: stroppy.Generation.Rules.StringRule.alphabet:type_name -> stroppy.Generation.Alphabet
	20, // 44: stroppy.Generation.Rules.StringRule.len_range:type_name -> stroppy.Generation.Range.UInt64Range
	22, // 45: stroppy.Generation.Rules.DateTimeRule.range:type_name -> stroppy.Generation.Range.DateTimeRange
	4,  // 46: stroppy.Generation.Rules.DateTimeRule.constant:type_name -> stroppy.DateTime
	3,  // 47: stroppy.Generation.Rules.UuidRule.constant:type_name -> stroppy.Uuid
	21, // 48: stroppy.Generation.Rules.DecimalRule.range:type_name -> stroppy.Generation.Range.DecimalRange
	2,  // 49: stroppy.Generation.Rules.DecimalRule.constant:type_name -> stroppy.Decimal
	50, // [50:50] is the sub-list for method output_type
	50, // [50:50] is the sub-list for method input_type
	50, // [50:50] is the sub-list for extension type_name
	50, // [50:50] is the sub-list for extension extendee
	0,  // [0:50] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[3].OneofWrappers = []any{
		(*Value_Null)(nil),
		(*Value_Int32)(nil),
		(*Value_Uint32)(nil),
		(*Value_Int64)(nil),
		(*Value_Uint64)(nil),
		(*Value_Float)(nil),
		(*Value_Double)(nil),
		(*Value_String_)(nil),
		(*Value_Bool)(nil),
		(*Value_Decimal)(nil),
		(*Value_Uuid)(nil),
		(*Value_Datetime)(nil),
		(*Value_Struct_)(nil),
		(*Value_List_)(nil),
	}
	file_common_proto_msgTypes[11].OneofWrappers = []any{
		(*Generation_Rule_FloatRules)(nil),
		(*Generation_Rule_DoubleRules)(nil),
		(*Generation_Rule_Int32Rules)(nil),
		(*Generation_Rule_Int64Rules)(nil),
		(*Generation_Rule_Uint32Rules)(nil),
		(*Generation_Rule_Uint64Rules)(nil),
		(*Generation_Rule_BoolRules)(nil),
		(*Generation_Rule_StringRules)(nil),
		(*Generation_Rule_DatetimeRules)(nil),
		(*Generation_Rule_UuidRules)(nil),
		(*Generation_Rule_DecimalRules)(nil),
	}
	file_common_proto_msgTypes[19].OneofWrappers = []any{
		(*Generation_Range_DecimalRange_Default_)(nil),
		(*Generation_Range_DecimalRange_Float)(nil),
		(*Generation_Range_DecimalRange_Double)(nil),
		(*Generation_Range_DecimalRange_String_)(nil),
	}
	file_common_proto_msgTypes[20].OneofWrappers = []any{
		(*Generation_Range_DateTimeRange_Default_)(nil),
		(*Generation_Range_DateTimeRange_String_)(nil),
		(*Generation_Range_DateTimeRange_TimestampPb_)(nil),
		(*Generation_Range_DateTimeRange_Timestamp_)(nil),
	}
	file_common_proto_msgTypes[25].OneofWrappers = []any{}
	file_common_proto_msgTypes[26].OneofWrappers = []any{}
	file_common_proto_msgTypes[27].OneofWrappers = []any{}
	file_common_proto_msgTypes[28].OneofWrappers = []any{}
	file_common_proto_msgTypes[29].OneofWrappers = []any{}
	file_common_proto_msgTypes[30].OneofWrappers = []any{}
	file_common_proto_msgTypes[31].OneofWrappers = []any{}
	file_common_proto_msgTypes[32].OneofWrappers = []any{}
	file_common_proto_msgTypes[33].OneofWrappers = []any{}
	file_common_proto_msgTypes[34].OneofWrappers = []any{}
	file_common_proto_msgTypes[35].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
