// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.23.4
// source: plugins.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// BuildQueriesContext provides the context needed to build database queries.
type BuildQueriesContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *StepContext           `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Query         *StepQueryDescriptor   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildQueriesContext) Reset() {
	*x = BuildQueriesContext{}
	mi := &file_plugins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildQueriesContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildQueriesContext) ProtoMessage() {}

func (x *BuildQueriesContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildQueriesContext.ProtoReflect.Descriptor instead.
func (*BuildQueriesContext) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{0}
}

func (x *BuildQueriesContext) GetContext() *StepContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BuildQueriesContext) GetQuery() *StepQueryDescriptor {
	if x != nil {
		return x.Query
	}
	return nil
}

// *
// DriverQuery represents a query that can be executed by a database driver.
type DriverQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Request       string                 `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Params        []*Value               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverQuery) Reset() {
	*x = DriverQuery{}
	mi := &file_plugins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverQuery) ProtoMessage() {}

func (x *DriverQuery) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverQuery.ProtoReflect.Descriptor instead.
func (*DriverQuery) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{1}
}

func (x *DriverQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverQuery) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *DriverQuery) GetParams() []*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

// *
// DriverQueriesList is a collection of DriverQuery messages.
type DriverQueriesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*DriverQuery         `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverQueriesList) Reset() {
	*x = DriverQueriesList{}
	mi := &file_plugins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverQueriesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverQueriesList) ProtoMessage() {}

func (x *DriverQueriesList) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverQueriesList.ProtoReflect.Descriptor instead.
func (*DriverQueriesList) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{2}
}

func (x *DriverQueriesList) GetQueries() []*DriverQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

var File_plugins_proto protoreflect.FileDescriptor

const file_plugins_proto_rawDesc = "" +
	"\n" +
	"\rplugins.proto\x12\astroppy\x1a\fcommon.proto\x1a\fconfig.proto\x1a\x10descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\"y\n" +
	"\x13BuildQueriesContext\x12.\n" +
	"\acontext\x18\x01 \x01(\v2\x14.stroppy.StepContextR\acontext\x122\n" +
	"\x05query\x18\x02 \x01(\v2\x1c.stroppy.StepQueryDescriptorR\x05query\"c\n" +
	"\vDriverQuery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arequest\x18\x02 \x01(\tR\arequest\x12&\n" +
	"\x06params\x18\x03 \x03(\v2\x0e.stroppy.ValueR\x06params\"C\n" +
	"\x11DriverQueriesList\x12.\n" +
	"\aqueries\x18\x01 \x03(\v2\x14.stroppy.DriverQueryR\aqueries2\x8a\x02\n" +
	"\fDriverPlugin\x12:\n" +
	"\n" +
	"Initialize\x12\x14.stroppy.StepContext\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\fBuildQueries\x12\x1c.stroppy.BuildQueriesContext\x1a\x1a.stroppy.DriverQueriesList\x128\n" +
	"\bRunQuery\x12\x14.stroppy.DriverQuery\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bTeardown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB'Z%github.com/picodata/stroppy/pkg/protob\x06proto3"

var (
	file_plugins_proto_rawDescOnce sync.Once
	file_plugins_proto_rawDescData []byte
)

func file_plugins_proto_rawDescGZIP() []byte {
	file_plugins_proto_rawDescOnce.Do(func() {
		file_plugins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)))
	})
	return file_plugins_proto_rawDescData
}

var file_plugins_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugins_proto_goTypes = []any{
	(*BuildQueriesContext)(nil), // 0: stroppy.BuildQueriesContext
	(*DriverQuery)(nil),         // 1: stroppy.DriverQuery
	(*DriverQueriesList)(nil),   // 2: stroppy.DriverQueriesList
	(*StepContext)(nil),         // 3: stroppy.StepContext
	(*StepQueryDescriptor)(nil), // 4: stroppy.StepQueryDescriptor
	(*Value)(nil),               // 5: stroppy.Value
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_plugins_proto_depIdxs = []int32{
	3, // 0: stroppy.BuildQueriesContext.context:type_name -> stroppy.StepContext
	4, // 1: stroppy.BuildQueriesContext.query:type_name -> stroppy.StepQueryDescriptor
	5, // 2: stroppy.DriverQuery.params:type_name -> stroppy.Value
	1, // 3: stroppy.DriverQueriesList.queries:type_name -> stroppy.DriverQuery
	3, // 4: stroppy.DriverPlugin.Initialize:input_type -> stroppy.StepContext
	0, // 5: stroppy.DriverPlugin.BuildQueries:input_type -> stroppy.BuildQueriesContext
	1, // 6: stroppy.DriverPlugin.RunQuery:input_type -> stroppy.DriverQuery
	6, // 7: stroppy.DriverPlugin.Teardown:input_type -> google.protobuf.Empty
	6, // 8: stroppy.DriverPlugin.Initialize:output_type -> google.protobuf.Empty
	2, // 9: stroppy.DriverPlugin.BuildQueries:output_type -> stroppy.DriverQueriesList
	6, // 10: stroppy.DriverPlugin.RunQuery:output_type -> google.protobuf.Empty
	6, // 11: stroppy.DriverPlugin.Teardown:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugins_proto_init() }
func file_plugins_proto_init() {
	if File_plugins_proto != nil {
		return
	}
	file_common_proto_init()
	file_config_proto_init()
	file_descriptor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_proto_goTypes,
		DependencyIndexes: file_plugins_proto_depIdxs,
		MessageInfos:      file_plugins_proto_msgTypes,
	}.Build()
	File_plugins_proto = out.File
	file_plugins_proto_goTypes = nil
	file_plugins_proto_depIdxs = nil
}
