// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.23.4
// source: plugins.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// UnitBuildContext provides the context needed to build a unit from a StepUnitDescriptor.
type UnitBuildContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *StepContext           `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Unit          *StepUnitDescriptor    `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitBuildContext) Reset() {
	*x = UnitBuildContext{}
	mi := &file_plugins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitBuildContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitBuildContext) ProtoMessage() {}

func (x *UnitBuildContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitBuildContext.ProtoReflect.Descriptor instead.
func (*UnitBuildContext) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{0}
}

func (x *UnitBuildContext) GetContext() *StepContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UnitBuildContext) GetUnit() *StepUnitDescriptor {
	if x != nil {
		return x.Unit
	}
	return nil
}

// *
// DriverQuery represents a query that can be executed by a database driver.
type DriverQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Request       string                 `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Params        []*Value               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverQuery) Reset() {
	*x = DriverQuery{}
	mi := &file_plugins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverQuery) ProtoMessage() {}

func (x *DriverQuery) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverQuery.ProtoReflect.Descriptor instead.
func (*DriverQuery) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{1}
}

func (x *DriverQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverQuery) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *DriverQuery) GetParams() []*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

// *
// DriverTransaction represents a transaction that can be executed by a database driver.
type DriverTransaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Queries        []*DriverQuery         `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	IsolationLevel TxIsolationLevel       `protobuf:"varint,2,opt,name=isolation_level,json=isolationLevel,proto3,enum=stroppy.TxIsolationLevel" json:"isolation_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DriverTransaction) Reset() {
	*x = DriverTransaction{}
	mi := &file_plugins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverTransaction) ProtoMessage() {}

func (x *DriverTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverTransaction.ProtoReflect.Descriptor instead.
func (*DriverTransaction) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{2}
}

func (x *DriverTransaction) GetQueries() []*DriverQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *DriverTransaction) GetIsolationLevel() TxIsolationLevel {
	if x != nil {
		return x.IsolationLevel
	}
	return TxIsolationLevel_TX_ISOLATION_LEVEL_UNSPECIFIED
}

// *
// DriverTransactionList is a list of transactions.
type DriverTransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*DriverTransaction   `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverTransactionList) Reset() {
	*x = DriverTransactionList{}
	mi := &file_plugins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverTransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverTransactionList) ProtoMessage() {}

func (x *DriverTransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverTransactionList.ProtoReflect.Descriptor instead.
func (*DriverTransactionList) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{3}
}

func (x *DriverTransactionList) GetTransactions() []*DriverTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_plugins_proto protoreflect.FileDescriptor

const file_plugins_proto_rawDesc = "" +
	"\n" +
	"\rplugins.proto\x12\astroppy\x1a\fcommon.proto\x1a\fconfig.proto\x1a\x10descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\"s\n" +
	"\x10UnitBuildContext\x12.\n" +
	"\acontext\x18\x01 \x01(\v2\x14.stroppy.StepContextR\acontext\x12/\n" +
	"\x04unit\x18\x02 \x01(\v2\x1b.stroppy.StepUnitDescriptorR\x04unit\"c\n" +
	"\vDriverQuery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arequest\x18\x02 \x01(\tR\arequest\x12&\n" +
	"\x06params\x18\x03 \x03(\v2\x0e.stroppy.ValueR\x06params\"\x87\x01\n" +
	"\x11DriverTransaction\x12.\n" +
	"\aqueries\x18\x01 \x03(\v2\x14.stroppy.DriverQueryR\aqueries\x12B\n" +
	"\x0fisolation_level\x18\x02 \x01(\x0e2\x19.stroppy.TxIsolationLevelR\x0eisolationLevel\"W\n" +
	"\x15DriverTransactionList\x12>\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1a.stroppy.DriverTransactionR\ftransactions2\x80\x03\n" +
	"\fDriverPlugin\x12:\n" +
	"\n" +
	"Initialize\x12\x14.stroppy.StepContext\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x19BuildTransactionsFromUnit\x12\x19.stroppy.UnitBuildContext\x1a\x1e.stroppy.DriverTransactionList\x12Z\n" +
	"\x1fBuildTransactionsFromUnitStream\x12\x19.stroppy.UnitBuildContext\x1a\x1a.stroppy.DriverTransaction0\x01\x12D\n" +
	"\x0eRunTransaction\x12\x1a.stroppy.DriverTransaction\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bTeardown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty2\xff\x01\n" +
	"\rSidecarPlugin\x12:\n" +
	"\n" +
	"Initialize\x12\x14.stroppy.StepContext\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\vOnStepStart\x12\x14.stroppy.StepContext\x1a\x16.google.protobuf.Empty\x129\n" +
	"\tOnStepEnd\x12\x14.stroppy.StepContext\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bTeardown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB.Z,github.com/stroppy-io/stroppy-core/pkg/protob\x06proto3"

var (
	file_plugins_proto_rawDescOnce sync.Once
	file_plugins_proto_rawDescData []byte
)

func file_plugins_proto_rawDescGZIP() []byte {
	file_plugins_proto_rawDescOnce.Do(func() {
		file_plugins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)))
	})
	return file_plugins_proto_rawDescData
}

var file_plugins_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugins_proto_goTypes = []any{
	(*UnitBuildContext)(nil),      // 0: stroppy.UnitBuildContext
	(*DriverQuery)(nil),           // 1: stroppy.DriverQuery
	(*DriverTransaction)(nil),     // 2: stroppy.DriverTransaction
	(*DriverTransactionList)(nil), // 3: stroppy.DriverTransactionList
	(*StepContext)(nil),           // 4: stroppy.StepContext
	(*StepUnitDescriptor)(nil),    // 5: stroppy.StepUnitDescriptor
	(*Value)(nil),                 // 6: stroppy.Value
	(TxIsolationLevel)(0),         // 7: stroppy.TxIsolationLevel
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_plugins_proto_depIdxs = []int32{
	4,  // 0: stroppy.UnitBuildContext.context:type_name -> stroppy.StepContext
	5,  // 1: stroppy.UnitBuildContext.unit:type_name -> stroppy.StepUnitDescriptor
	6,  // 2: stroppy.DriverQuery.params:type_name -> stroppy.Value
	1,  // 3: stroppy.DriverTransaction.queries:type_name -> stroppy.DriverQuery
	7,  // 4: stroppy.DriverTransaction.isolation_level:type_name -> stroppy.TxIsolationLevel
	2,  // 5: stroppy.DriverTransactionList.transactions:type_name -> stroppy.DriverTransaction
	4,  // 6: stroppy.DriverPlugin.Initialize:input_type -> stroppy.StepContext
	0,  // 7: stroppy.DriverPlugin.BuildTransactionsFromUnit:input_type -> stroppy.UnitBuildContext
	0,  // 8: stroppy.DriverPlugin.BuildTransactionsFromUnitStream:input_type -> stroppy.UnitBuildContext
	2,  // 9: stroppy.DriverPlugin.RunTransaction:input_type -> stroppy.DriverTransaction
	8,  // 10: stroppy.DriverPlugin.Teardown:input_type -> google.protobuf.Empty
	4,  // 11: stroppy.SidecarPlugin.Initialize:input_type -> stroppy.StepContext
	4,  // 12: stroppy.SidecarPlugin.OnStepStart:input_type -> stroppy.StepContext
	4,  // 13: stroppy.SidecarPlugin.OnStepEnd:input_type -> stroppy.StepContext
	8,  // 14: stroppy.SidecarPlugin.Teardown:input_type -> google.protobuf.Empty
	8,  // 15: stroppy.DriverPlugin.Initialize:output_type -> google.protobuf.Empty
	3,  // 16: stroppy.DriverPlugin.BuildTransactionsFromUnit:output_type -> stroppy.DriverTransactionList
	2,  // 17: stroppy.DriverPlugin.BuildTransactionsFromUnitStream:output_type -> stroppy.DriverTransaction
	8,  // 18: stroppy.DriverPlugin.RunTransaction:output_type -> google.protobuf.Empty
	8,  // 19: stroppy.DriverPlugin.Teardown:output_type -> google.protobuf.Empty
	8,  // 20: stroppy.SidecarPlugin.Initialize:output_type -> google.protobuf.Empty
	8,  // 21: stroppy.SidecarPlugin.OnStepStart:output_type -> google.protobuf.Empty
	8,  // 22: stroppy.SidecarPlugin.OnStepEnd:output_type -> google.protobuf.Empty
	8,  // 23: stroppy.SidecarPlugin.Teardown:output_type -> google.protobuf.Empty
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugins_proto_init() }
func file_plugins_proto_init() {
	if File_plugins_proto != nil {
		return
	}
	file_common_proto_init()
	file_config_proto_init()
	file_descriptor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugins_proto_goTypes,
		DependencyIndexes: file_plugins_proto_depIdxs,
		MessageInfos:      file_plugins_proto_msgTypes,
	}.Build()
	File_plugins_proto = out.File
	file_plugins_proto_goTypes = nil
	file_plugins_proto_depIdxs = nil
}
