// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: plugins.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BuildQueriesContext with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BuildQueriesContext) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BuildQueriesContext with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BuildQueriesContextMultiError, or nil if none found.
func (m *BuildQueriesContext) ValidateAll() error {
	return m.validate(true)
}

func (m *BuildQueriesContext) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BuildQueriesContextValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BuildQueriesContextValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BuildQueriesContextValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetQuery()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BuildQueriesContextValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BuildQueriesContextValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQuery()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BuildQueriesContextValidationError{
				field:  "Query",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BuildQueriesContextMultiError(errors)
	}

	return nil
}

// BuildQueriesContextMultiError is an error wrapping multiple validation
// errors returned by BuildQueriesContext.ValidateAll() if the designated
// constraints aren't met.
type BuildQueriesContextMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BuildQueriesContextMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BuildQueriesContextMultiError) AllErrors() []error { return m }

// BuildQueriesContextValidationError is the validation error returned by
// BuildQueriesContext.Validate if the designated constraints aren't met.
type BuildQueriesContextValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BuildQueriesContextValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BuildQueriesContextValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BuildQueriesContextValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BuildQueriesContextValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BuildQueriesContextValidationError) ErrorName() string {
	return "BuildQueriesContextValidationError"
}

// Error satisfies the builtin error interface
func (e BuildQueriesContextValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBuildQueriesContext.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BuildQueriesContextValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BuildQueriesContextValidationError{}

// Validate checks the field values on DriverQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DriverQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DriverQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DriverQueryMultiError, or
// nil if none found.
func (m *DriverQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *DriverQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Request

	for idx, item := range m.GetParams() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DriverQueryValidationError{
						field:  fmt.Sprintf("Params[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DriverQueryValidationError{
						field:  fmt.Sprintf("Params[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DriverQueryValidationError{
					field:  fmt.Sprintf("Params[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DriverQueryMultiError(errors)
	}

	return nil
}

// DriverQueryMultiError is an error wrapping multiple validation errors
// returned by DriverQuery.ValidateAll() if the designated constraints aren't met.
type DriverQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DriverQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DriverQueryMultiError) AllErrors() []error { return m }

// DriverQueryValidationError is the validation error returned by
// DriverQuery.Validate if the designated constraints aren't met.
type DriverQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DriverQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DriverQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DriverQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DriverQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DriverQueryValidationError) ErrorName() string { return "DriverQueryValidationError" }

// Error satisfies the builtin error interface
func (e DriverQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDriverQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DriverQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DriverQueryValidationError{}

// Validate checks the field values on DriverQueriesList with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DriverQueriesList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DriverQueriesList with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DriverQueriesListMultiError, or nil if none found.
func (m *DriverQueriesList) ValidateAll() error {
	return m.validate(true)
}

func (m *DriverQueriesList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetQueries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DriverQueriesListValidationError{
						field:  fmt.Sprintf("Queries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DriverQueriesListValidationError{
						field:  fmt.Sprintf("Queries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DriverQueriesListValidationError{
					field:  fmt.Sprintf("Queries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DriverQueriesListMultiError(errors)
	}

	return nil
}

// DriverQueriesListMultiError is an error wrapping multiple validation errors
// returned by DriverQueriesList.ValidateAll() if the designated constraints
// aren't met.
type DriverQueriesListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DriverQueriesListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DriverQueriesListMultiError) AllErrors() []error { return m }

// DriverQueriesListValidationError is the validation error returned by
// DriverQueriesList.Validate if the designated constraints aren't met.
type DriverQueriesListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DriverQueriesListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DriverQueriesListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DriverQueriesListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DriverQueriesListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DriverQueriesListValidationError) ErrorName() string {
	return "DriverQueriesListValidationError"
}

// Error satisfies the builtin error interface
func (e DriverQueriesListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDriverQueriesList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DriverQueriesListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DriverQueriesListValidationError{}
