// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: plugins.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UnitBuildContext with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UnitBuildContext) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnitBuildContext with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UnitBuildContextMultiError, or nil if none found.
func (m *UnitBuildContext) ValidateAll() error {
	return m.validate(true)
}

func (m *UnitBuildContext) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UnitBuildContextValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UnitBuildContextValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UnitBuildContextValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUnit()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UnitBuildContextValidationError{
					field:  "Unit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UnitBuildContextValidationError{
					field:  "Unit",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUnit()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UnitBuildContextValidationError{
				field:  "Unit",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UnitBuildContextMultiError(errors)
	}

	return nil
}

// UnitBuildContextMultiError is an error wrapping multiple validation errors
// returned by UnitBuildContext.ValidateAll() if the designated constraints
// aren't met.
type UnitBuildContextMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnitBuildContextMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnitBuildContextMultiError) AllErrors() []error { return m }

// UnitBuildContextValidationError is the validation error returned by
// UnitBuildContext.Validate if the designated constraints aren't met.
type UnitBuildContextValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnitBuildContextValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnitBuildContextValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnitBuildContextValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnitBuildContextValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnitBuildContextValidationError) ErrorName() string { return "UnitBuildContextValidationError" }

// Error satisfies the builtin error interface
func (e UnitBuildContextValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnitBuildContext.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnitBuildContextValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnitBuildContextValidationError{}

// Validate checks the field values on DriverQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DriverQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DriverQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DriverQueryMultiError, or
// nil if none found.
func (m *DriverQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *DriverQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Request

	for idx, item := range m.GetParams() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DriverQueryValidationError{
						field:  fmt.Sprintf("Params[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DriverQueryValidationError{
						field:  fmt.Sprintf("Params[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DriverQueryValidationError{
					field:  fmt.Sprintf("Params[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DriverQueryMultiError(errors)
	}

	return nil
}

// DriverQueryMultiError is an error wrapping multiple validation errors
// returned by DriverQuery.ValidateAll() if the designated constraints aren't met.
type DriverQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DriverQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DriverQueryMultiError) AllErrors() []error { return m }

// DriverQueryValidationError is the validation error returned by
// DriverQuery.Validate if the designated constraints aren't met.
type DriverQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DriverQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DriverQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DriverQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DriverQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DriverQueryValidationError) ErrorName() string { return "DriverQueryValidationError" }

// Error satisfies the builtin error interface
func (e DriverQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDriverQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DriverQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DriverQueryValidationError{}

// Validate checks the field values on DriverTransaction with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DriverTransaction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DriverTransaction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DriverTransactionMultiError, or nil if none found.
func (m *DriverTransaction) ValidateAll() error {
	return m.validate(true)
}

func (m *DriverTransaction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetQueries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DriverTransactionValidationError{
						field:  fmt.Sprintf("Queries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DriverTransactionValidationError{
						field:  fmt.Sprintf("Queries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DriverTransactionValidationError{
					field:  fmt.Sprintf("Queries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for IsolationLevel

	if len(errors) > 0 {
		return DriverTransactionMultiError(errors)
	}

	return nil
}

// DriverTransactionMultiError is an error wrapping multiple validation errors
// returned by DriverTransaction.ValidateAll() if the designated constraints
// aren't met.
type DriverTransactionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DriverTransactionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DriverTransactionMultiError) AllErrors() []error { return m }

// DriverTransactionValidationError is the validation error returned by
// DriverTransaction.Validate if the designated constraints aren't met.
type DriverTransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DriverTransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DriverTransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DriverTransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DriverTransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DriverTransactionValidationError) ErrorName() string {
	return "DriverTransactionValidationError"
}

// Error satisfies the builtin error interface
func (e DriverTransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDriverTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DriverTransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DriverTransactionValidationError{}

// Validate checks the field values on DriverTransactionList with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DriverTransactionList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DriverTransactionList with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DriverTransactionListMultiError, or nil if none found.
func (m *DriverTransactionList) ValidateAll() error {
	return m.validate(true)
}

func (m *DriverTransactionList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTransactions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DriverTransactionListValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DriverTransactionListValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DriverTransactionListValidationError{
					field:  fmt.Sprintf("Transactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DriverTransactionListMultiError(errors)
	}

	return nil
}

// DriverTransactionListMultiError is an error wrapping multiple validation
// errors returned by DriverTransactionList.ValidateAll() if the designated
// constraints aren't met.
type DriverTransactionListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DriverTransactionListMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DriverTransactionListMultiError) AllErrors() []error { return m }

// DriverTransactionListValidationError is the validation error returned by
// DriverTransactionList.Validate if the designated constraints aren't met.
type DriverTransactionListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DriverTransactionListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DriverTransactionListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DriverTransactionListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DriverTransactionListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DriverTransactionListValidationError) ErrorName() string {
	return "DriverTransactionListValidationError"
}

// Error satisfies the builtin error interface
func (e DriverTransactionListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDriverTransactionList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DriverTransactionListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DriverTransactionListValidationError{}
