name: CI

on:
  push:
  pull_request:

jobs:
  golang-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install linter dependencies
        run: make .bin-deps

      - name: Run linter
        run: make linter

      - name: Run tests
        run: make tests
